# Workflow pour déployer du contenu HTML statique vers GitHub Pages
name: Deploy static content to Pages

on:
  # S'exécute sur les pushs vers la branche par défaut
  push:
    branches: ["master"]

  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions GITHUB_TOKEN pour permettre le déploiement vers GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet un seul déploiement concurrent
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de déploiement unique
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload du dossier public
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
